export const companyProfile = {
  brandIdea: [
    "Altheon Tours & Travel is more than a traditional tours and travel agency. Altheon is a travel, events and experience-management company designed to remove the burden of planning, booking and coordinating travel, meetings, events and experiences.",
    "Our clients tell us what they need and trust Altheon to take care of the details. Whether it is an urgent business trip, a corporate meeting, a team gathering, a couple's getaway or a group holiday, Altheon coordinates the arrangements so the client can focus on what matters.",
  ],
  promise: {
    headline: "You bring the plan. We make the arrangements. You enjoy the experience.",
    problem: "I don't have the time to organise this.",
    answer: "Altheon provides convenient, professional and end-to-end travel and experience solutions.",
  },
  differentiators: [
    "We do not simply sell tickets; we create travel solutions.",
    "We save clients time by coordinating multiple travel and event requirements through one partner.",
    "We combine travel, accommodation, meetings, events and experiences.",
    "We provide solutions for urgent requests and carefully planned journeys.",
    "We create personalised experiences rather than one-size-fits-all packages.",
    "We are designed to serve both corporate and leisure clients.",
  ],
  values: [
    { name: "Efficiency", description: "We value our clients' time and provide timely, practical and effective solutions." },
    { name: "Reliability", description: "When clients entrust a request to Altheon, we take responsibility for getting it done." },
    { name: "Commitment", description: "We take ownership of client needs from planning and booking through coordination and support." },
    { name: "Professionalism", description: "Every client interaction, booking, proposal, itinerary and event is handled professionally." },
    { name: "Bold & Energetic", description: "We bring energy, confidence and a positive attitude to every request and experience." },
    { name: "Innovation", description: "We look for smarter, creative and convenient ways to solve travel and experience challenges." },
    { name: "Customer-Centricity", description: "We start with the client's needs, preferences and objectives and build the solution around them." },
    { name: "Creativity", description: "We believe travel, meetings and events should be purposeful, memorable and engaging." },
    { name: "Accountability", description: "Once we accept a client's request, we take ownership of delivering the agreed solution." },
  ],
  philosophy: "We don't just book trips. We create solutions. From the moment an idea is shared with us to the moment the client completes the journey or event, Altheon takes care of the details.",
  process: [
    "Tell us what you need.",
    "We understand your objective, preferences, timing and budget.",
    "We design the most suitable solution.",
    "We coordinate bookings, suppliers and arrangements.",
    "We provide a clear itinerary and relevant information.",
    "We remain available for support within the agreed scope.",
    "We follow up and use client feedback to improve future experiences.",
  ],
  targetClients: [
    "Corporate organisations",
    "Small and medium-sized enterprises (SMEs)",
    "Hybrid and remote companies",
    "NGOs and development organisations",
    "Executives and professionals",
    "Couples and honeymooners",
    "Families",
    "Friends and social groups",
    "Corporate and institutional groups",
  ],
};

export const services = [
  {
    slug: "hotel-accommodation",
    shortName: "Hotel & Accommodation",
    name: "Hotel & Accommodation",
    eyebrow: "Stay well, wherever you go",
    cardDescription: "Comfort, Luxury and Unforgettable stays from check in to check out.",
    intro: "Hotels, lodges, resorts and serviced stays selected around your destination, budget, comfort and reason for travelling.",
    image: "/quang-nguyen-vinh.jpeg",
    cardImage: "/rachel.jpeg",
    services: [
      "Domestic and international hotel bookings",
      "Safari lodges and tented camps",
      "Beach resorts and holiday properties",
      "Serviced apartments and extended stays",
      "Corporate and executive accommodation",
      "Group room blocks",
      "Honeymoon and special-occasion stays",
      "Booking changes and accommodation support",
    ],
    audience: ["Business travellers", "Couples and families", "Groups and organisations", "Long-stay travellers"],
    outcome: "The right place to stay, selected for the purpose of your trip and coordinated with the rest of your journey.",
    sections: [
      { title: "More than finding a room", text: "Share where you are going, who is travelling and what matters most. We identify suitable properties and coordinate the confirmed stay so location, comfort and budget work together." },
      { title: "Connected to the journey", text: "Accommodation works best when it fits the flights, transfers, activities and schedule around it. Altheon keeps those details aligned instead of treating the stay as an isolated booking." },
    ],
    showcase: {
      eyebrow: "Choosing Well",
      heading: "Where you stay changes the journey.",
      lead: "Accommodation is one of the most important decisions in planning your trip — not simply a question of price, but of atmosphere, location and how you want each day to feel.",
      notes: [
        "A lodge offers the solidity and services of a traditional hotel. A tented camp brings you closer to the landscape, with proper beds, en-suite bathrooms and comfort just beyond the canvas.",
        "This collection reflects properties we know and use often, but it isn't a limit — we can work with virtually any hotel, lodge or camp in Kenya and match each night to your route, budget and preferred level of comfort.",
      ],
    },
    gallery: {
      eyebrow: "Handpicked Favourites",
      heading: "Beautiful places.",
      accent: "Genuine character.",
      blurb: "From intimate tented camps to landmark lodges and coastal hideaways — a look at the range of places we can arrange for your stay.",
      images: [
        { src: "/gallary1.png", alt: "Warmly lit lodge bedroom with garden views", size: "large" },
        { src: "/gallary2.png", alt: "Twin-bed tented suite with en-suite bathroom", caption: "lake elementaita manor" },
        { src: "/gallary3.png", alt: "Private timber deck of a tented camp among palm trees", caption: "Mukima Manor" },
        { src: "/gallary4.png", alt: "Resort pool and loungers beneath palm trees", caption: "elementaita nature pebbles" },
        { src: "/gallary5.png", alt: "Moon camp", caption: "moon's camp" },
        { src: "/kibo.png", alt: "Kibo camp", caption: "Kibo camp" },
        { src: "/maiyan.png", alt: "Maiyan", caption: "Maiyan" },
        { src: "/lerruat.png", alt: "Lerruat", caption: "Lerruat Log Resort" },
        { src: "/amboseli.png", alt: "Amboseli", caption: "AA Amboseli" },
        { src: "/woodsy.png", alt: "Woodsy", caption: "Woodsy Resort" },
      ],
    },
  },
  {
    slug: "safari-wildlife",
    shortName: "Safari & Wildlife",
    name: "Safari & Wildlife",
    eyebrow: "Experience the wild",
    cardDescription: "Thoughtfully designed safaris across Kenya's parks, reserves and conservancies.",
    intro: "Personalised wildlife journeys that bring together the right destinations, stays, guides and pace for a memorable safari.",
    image: "/kilimanjaro_elephant.jpg",
    cardImage: "/kilimanjaro_elephant.jpg",
    services: [
      "Tailor-made safari itineraries",
      "National park, reserve and conservancy planning",
      "Safari lodges and tented camps",
      "Professional guides and game drives",
      "Road transfers and domestic air connections",
      "Park-fee and entry coordination",
      "Private, family and group safaris",
      "Beach and city extensions",
    ],
    audience: ["First-time safari travellers", "Couples and families", "Wildlife enthusiasts", "Private and organised groups"],
    outcome: "A safari built around how you want to experience the landscape, wildlife and rhythm of Kenya.",
    sections: [
      { title: "The right safari for you", text: "A safari can be adventurous, relaxed, family-friendly or deeply focused on wildlife. We shape the route, accommodation and daily rhythm around your interests, available time and preferred comfort." },
      { title: "Local knowledge in every detail", text: "Seasons, distances and park combinations affect the quality of a safari. We use local insight to connect the destinations and practical arrangements into one coherent journey." },
    ],
  },
  {
    slug: "travel-desk",
    shortName: "Travel Desk",
    name: "Travel Desk",
    eyebrow: "Plan. Book. Move.",
    cardDescription: "Where every adventure begins.",
    intro: "A responsive travel desk for everyday bookings, complete itineraries and urgent movement—managed through one reliable point of contact.",
    image: "/Kenya_Airways_Flight.jpg",
    cardImage: "/Kenya_Airways_Flight.jpg",
    services: [
      "Domestic and international flight bookings",
      "Airport transfers",
      "Travel planning and itineraries",
      "Urgent and last-minute travel arrangements",
      "Ticket changes and rebooking support",
      "Travel consultancy",
      "Travel-related coordination and support",
    ],
    audience: ["Executives and professionals", "Families and leisure travellers", "Corporate and institutional groups"],
    outcome: "One place to manage the bookings, movements and information behind a smooth trip.",
    sections: [
      { title: "Travel without the admin", text: "Share the destination, timing and purpose of your trip. Altheon coordinates the practical details, presents suitable options and keeps the agreed arrangements together so you do not have to chase multiple providers." },
      { title: "Planned or last-minute", text: "Some journeys begin months ahead; others begin with an urgent call. We support both carefully planned travel and time-sensitive requests, working within available supplier options to find a practical solution." },
    ],
  },
  {
    slug: "corporate",
    shortName: "Corporate",
    name: "Corporate Travel",
    eyebrow: "Move business forward",
    cardDescription: "Reliable travel solutions for employees, executives, clients and business meetings.",
    intro: "A practical travel and coordination partner for companies that need employees, executives, teams and clients to move and meet efficiently.",
    image: "/services-planning-journey.png",
    cardImage: "/services-planning-journey.png",
    services: [
      "Corporate travel management",
      "Business and executive travel",
      "Corporate accommodation",
      "Meeting rooms and conference venues",
      "Corporate retreats and off-sites",
      "Business and client visits",
      "Travel policy and itinerary support",
      "Corporate travel logistics",
    ],
    audience: ["Corporate organisations", "SMEs", "NGOs and development organisations", "Executives and professionals"],
    outcome: "Efficient business movement and meetings without burdening internal teams with supplier coordination.",
    sections: [
      { title: "A practical coordination partner", text: "Altheon helps companies move employees, executives, teams and clients efficiently. Travel, accommodation, venues and supporting logistics are managed as one connected requirement." },
      { title: "Built around the business objective", text: "A client visit, board meeting, conference or retreat has a purpose beyond travel. We start with that objective, then coordinate the arrangements needed to support it professionally." },
    ],
  },
  {
    slug: "holiday-leisure",
    shortName: "Holiday & Leisure",
    name: "Holiday & Leisure",
    eyebrow: "Time away, made personal",
    cardDescription: "Tailor-made holidays for couples, families, friends and solo travellers.",
    intro: "Personalised leisure journeys created around your pace, interests, occasion and the memories you want to bring home.",
    image: "/Diani_Beach_Sunrise_Kenya.jpg",
    cardImage: "/Diani_Beach_Sunrise_Kenya.jpg",
    services: [
      "Beach holidays and resort stays",
      "Couples' getaways",
      "Honeymoons and anniversaries",
      "Family holidays",
      "Friends' getaways",
      "City breaks and weekend escapes",
      "Wellness and relaxation experiences",
      "Curated activities and excursions",
    ],
    audience: ["Couples and honeymooners", "Families", "Friends", "Solo leisure travellers"],
    outcome: "A holiday shaped around the people travelling, not simply a room or a standard package.",
    sections: [
      { title: "Made around your time away", text: "A honeymoon, family holiday and weekend escape should not feel interchangeable. We build around the occasion, personalities, pace and experiences you want to share." },
      { title: "More than accommodation", text: "Where appropriate, your journey can include activities, special dinners, adventures, wellness moments and local experiences—coordinated as one complete holiday." },
    ],
  },
  {
    slug: "group-travel",
    shortName: "Group Travel",
    name: "Group Travel",
    eyebrow: "Move together, smoothly",
    cardDescription: "Coordinated journeys for friends, families, teams, delegates and organised groups.",
    intro: "Flights, rooms, transfers, schedules and shared activities coordinated as one clear plan for the whole group.",
    image: "/more-than-travel-safari-v2.png",
    cardImage: "/more-than-travel-safari-v2.png",
    services: [
      "Group flight coordination",
      "Group accommodation and rooming lists",
      "Coach, shuttle and transfer arrangements",
      "Group itineraries and activity planning",
      "Conference and delegate travel",
      "Family and friends' group holidays",
      "Team retreats and incentive travel",
      "On-trip group coordination and support",
    ],
    audience: ["Friends and families", "Corporate and institutional groups", "Conference delegates", "Clubs and organised travel groups"],
    outcome: "One coordinated journey that keeps every traveller, booking and movement working together.",
    sections: [
      { title: "Many travellers, one clear plan", text: "Group travel involves more than multiplying a booking. Names, arrival times, rooms, transfers and activities all need to stay aligned. Altheon brings them together through one coordination point." },
      { title: "Built around the group", text: "A family celebration, team retreat and conference delegation have different priorities. We shape the logistics and shared experiences around the group's purpose, size, timing and budget." },
    ],
  },
];

export const getService = (slug) => services.find((service) => service.slug === slug);
