export const companyProfile = {
  brandIdea: [
    "Altheon Tours & Travel is more than a traditional tours and travel agency. Altheon is a travel, events and experience-management company designed to remove the burden of planning, booking and coordinating travel, meetings, events and experiences.",
    "Our clients tell us what they need and trust Altheon to take care of the details. Whether it is an urgent business trip, a corporate meeting, a hybrid-team gathering, a couple's getaway or a group holiday, Altheon coordinates the arrangements so the client can focus on what matters.",
  ],
  promise: {
    headline: "You bring the plan. We make the arrangements. You enjoy the experience.",
    problem: "I don't have the time to organise this.",
    answer: "Altheon provides convenient, professional and end-to-end travel and experience solutions.",
  },
  differentiators: [
    "We do not simply sell tickets; we create travel solutions.",
    "We save clients time by coordinating multiple travel and event requirements through one partner.",
    "We combine travel, accommodation, meetings, events and experiences.",
    "We provide solutions for urgent requests and carefully planned journeys.",
    "We create personalised experiences rather than one-size-fits-all packages.",
    "We are designed to serve both corporate and leisure clients.",
  ],
  values: [
    { name: "Efficiency", description: "We value our clients' time and provide timely, practical and effective solutions." },
    { name: "Reliability", description: "When clients entrust a request to Altheon, we take responsibility for getting it done." },
    { name: "Commitment", description: "We take ownership of client needs from planning and booking through coordination and support." },
    { name: "Professionalism", description: "Every client interaction, booking, proposal, itinerary and event is handled professionally." },
    { name: "Bold & Energetic", description: "We bring energy, confidence and a positive attitude to every request and experience." },
    { name: "Innovation", description: "We look for smarter, creative and convenient ways to solve travel and experience challenges." },
    { name: "Customer-Centricity", description: "We start with the client's needs, preferences and objectives and build the solution around them." },
    { name: "Creativity", description: "We believe travel, meetings and events should be purposeful, memorable and engaging." },
    { name: "Accountability", description: "Once we accept a client's request, we take ownership of delivering the agreed solution." },
  ],
  philosophy: "We don't just book trips. We create solutions. From the moment an idea is shared with us to the moment the client completes the journey or event, Altheon takes care of the details.",
  process: [
    "Tell us what you need.",
    "We understand your objective, preferences, timing and budget.",
    "We design the most suitable solution.",
    "We coordinate bookings, suppliers and arrangements.",
    "We provide a clear itinerary and relevant information.",
    "We remain available for support within the agreed scope.",
    "We follow up and use client feedback to improve future experiences.",
  ],
  targetClients: [
    "Corporate organisations",
    "Small and medium-sized enterprises (SMEs)",
    "Hybrid and remote companies",
    "NGOs and development organisations",
    "Executives and professionals",
    "Couples and honeymooners",
    "Families",
    "Friends and social groups",
    "Corporate and institutional groups",
  ],
};

export const services = [
  {
    slug: "travel-desk",
    shortName: "Travel Desk",
    name: "A&T Travel Desk",
    eyebrow: "Plan. Book. Move.",
    intro: "A responsive travel desk for everyday bookings, complete itineraries and urgent movement—managed through one reliable point of contact.",
    image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1920&q=85",
    cardImage: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=900&q=80",
    services: [
      "Flight bookings",
      "Hotel and accommodation bookings",
      "Airport transfers",
      "Travel planning and itineraries",
      "Urgent and last-minute travel arrangements",
      "Travel consultancy",
      "Travel-related coordination and support",
    ],
    audience: ["Executives and professionals", "Families and leisure travellers", "Corporate and institutional groups"],
    outcome: "One place to manage the bookings, movements and information behind a smooth trip.",
    sections: [
      { title: "Travel without the admin", text: "Share the destination, timing and purpose of your trip. Altheon coordinates the practical details, presents suitable options and keeps the agreed arrangements together so you do not have to chase multiple providers." },
      { title: "Planned or last-minute", text: "Some journeys begin months ahead; others begin with an urgent call. We support both carefully planned travel and time-sensitive requests, working within available supplier options to find a practical solution." },
    ],
  },
  {
    slug: "corporate",
    shortName: "Corporate",
    name: "A&T Corporate",
    eyebrow: "Move business forward",
    intro: "A practical travel and coordination partner for companies that need employees, executives, teams and clients to move, meet and connect efficiently.",
    image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1920&q=85",
    cardImage: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=80",
    services: [
      "Corporate travel management",
      "Business and executive travel",
      "Corporate accommodation",
      "Meeting rooms, boardrooms and conference venues",
      "Corporate retreats and off-sites",
      "Conferences and workshops",
      "Corporate event logistics",
      "Business and client visits",
    ],
    audience: ["Corporate organisations", "SMEs", "NGOs and development organisations", "Executives and professionals"],
    outcome: "Efficient business movement and meetings without burdening internal teams with supplier coordination.",
    sections: [
      { title: "A practical coordination partner", text: "Altheon helps companies move employees, executives, teams and clients efficiently. Travel, accommodation, venues and supporting logistics are managed as one connected requirement rather than several disconnected bookings." },
      { title: "Built around the business objective", text: "A client visit, board meeting, conference or retreat has a purpose beyond travel. We start with that objective, then coordinate the arrangements needed to support it professionally." },
    ],
  },
  {
    slug: "hybrid",
    shortName: "Hybrid",
    name: "A&T Hybrid",
    eyebrow: "Bring distributed teams together",
    intro: "End-to-end coordination for short-term visits and gatherings that help remote and hybrid teams meet, work, connect and return home smoothly.",
    image: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1920&q=85",
    cardImage: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=900&q=80",
    services: [
      "Planning short-term company visits",
      "Bringing distributed and remote teams together",
      "Accommodation and transport coordination",
      "Meeting and conference venue arrangements",
      "Team-building and group activities",
      "Meals and social experiences",
      "End-to-end coordination for hybrid-company gatherings",
    ],
    audience: ["Hybrid and remote companies", "SMEs", "NGOs and development organisations", "Corporate and institutional groups"],
    outcome: "Your team deals with Altheon while Altheon coordinates the required suppliers and arrangements.",
    example: [
      { day: "Day 1", title: "Arrival & welcome", text: "Arrival, airport transfers, hotel check-in and welcome dinner." },
      { day: "Day 2", title: "Workshop & connection", text: "Conference venue, breakfast, workshop, lunch, team-building activity and dinner." },
      { day: "Day 3", title: "Strategy & departure", text: "Strategy meeting, lunch, checkout and departure transfers." },
    ],
    sections: [
      { title: "One team, one gathering, one partner", text: "For hybrid companies and SMEs, Altheon coordinates short-term visits, client meetings, team gatherings, retreats and corporate events without the company having to manage multiple suppliers." },
      { title: "Productivity and connection", text: "The working sessions matter, but so do the transitions, meals and shared experiences around them. We bring both sides together in one coherent gathering plan." },
    ],
  },
  {
    slug: "experiences",
    shortName: "Experiences",
    name: "A&T Experiences",
    eyebrow: "Travel that brings people closer",
    intro: "Personalised leisure experiences for couples, families, friends and groups—created around connection, celebration and lasting memories.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1920&q=85",
    cardImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80",
    services: [
      "Couples' getaways",
      "Honeymoons and anniversaries",
      "Romantic experiences",
      "Wedding and event travel",
      "Family holidays",
      "Friends' getaways",
      "Group experiences",
      "Curated activities and memorable experiences",
    ],
    audience: ["Couples and honeymooners", "Families", "Friends and social groups", "Wedding and celebration groups"],
    outcome: "An experience shaped around the people travelling, not simply a room or a standard package.",
    note: "Altheon's couple experiences are leisure and relationship-building activities. They are not counselling or therapy.",
    sections: [
      { title: "More than accommodation", text: "For couples, Altheon focuses on creating experiences rather than simply selling accommodation. Where appropriate, itineraries can include activities, games, conversation experiences, romantic dinners, adventures and wellness activities." },
      { title: "Personal to your people", text: "A honeymoon, family holiday and friends' getaway should not feel interchangeable. We build around the occasion, personalities, pace and memories you want to create together." },
    ],
  },
  {
    slug: "events",
    shortName: "Events",
    name: "A&T Events",
    eyebrow: "Purposeful events, coordinated well",
    intro: "The travel, venue, accommodation and movement behind meetings and events—planned as one complete operational brief.",
    image: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1920&q=85",
    cardImage: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=900&q=80",
    services: [
      "Corporate meetings",
      "Retreats",
      "Workshops",
      "Team-building events",
      "Conference logistics",
      "Venue sourcing",
      "Accommodation and transport coordination",
      "Event-related travel arrangements",
    ],
    audience: ["Corporate organisations", "SMEs", "NGOs and development organisations", "Corporate and institutional groups"],
    outcome: "A well-coordinated event in which the venue, people and supporting logistics work together.",
    sections: [
      { title: "The details behind the event", text: "A successful event relies on more than the programme. Venue suitability, arrival timing, accommodation, transfers and supplier coordination all shape the experience. Altheon brings those requirements into one plan." },
      { title: "Purposeful and memorable", text: "We believe meetings and events should be purposeful, memorable and engaging. Every solution is built around the objective, audience, timing and available budget." },
    ],
  },
];

export const getService = (slug) => services.find((service) => service.slug === slug);
